config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :articles
  resources :projects
  post 'welcome/contact', to: 'welcome#contact'

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author, class_name: 'User'

  def publish!
    published
    save!
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :technologies_used, presence: true
  validates :name, length: { in: 4..255 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles, foreign_key: 'author_id'

  def author?
    role == 'author'
  end

  def editor?
    role == 'editor'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    authorize @article
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    if @article.save
      current_user.articles << @article
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    authorize @article
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    authorize @article
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(
                   :title, :body, (:published if current_user.role == 'editor'))
  end

  def user_not_authorized
    flash[:notice] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/projects_controller.rb
# app/controllers/projects_controller
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
    @remote_value = true
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = 'Project has been created.'
      redirect_to @project
    else
      flash[:error] = 'Project could not be saved.'
      render :new
    end
  end

  def show
  end

  def edit
    @remote_value = false
  end

  def update
    if @project.update_attributes(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully deleted.'
  end

  private

  def project_params
    params.require(:project).permit(:name, :technologies_used)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

    def contact
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]

    h = JSON.generate({ 'name' => @name, 'email' => @email, 'message' => @message})
    PostmanWorker.perform_async(h, 5)

    # if instead of sidekiq I was just sending email from rails
    # UserMailer.contact_email(@name, @email, @message).deliver

    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then 'info'
    when :success then 'success'
    when :error then 'error'
    when :alert then 'warning'
    end
  end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %>
        prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <% if policy(@article).publish? %>
    <div class="field">
      <%= f.label(
        :published,
        title: "Is this article published?",
        data: { tooltip: true }) %><br>
      <%= f.check_box :published %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<table>
  <tbody>
    <% @articles.each do |article| %>
      <tr id="<%= dom_id(article) %>">
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td><%= link_to 'Show', article %></td>
      <% if policy(article).update? %>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <% end %>
      <% if policy(article).destroy? %>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p id="author">
  <b>By:</b>
  <%= @article.author.email %>
</p>

<p id="status">
  <b>Status:</b>
  <%= @article.published? ? "Published" : "Unpublished" %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', article_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>

<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Forrest Parker</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Home</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#">Right Button Active</a></li>

      <% if user_signed_in? %>
        <li class="has-dropdown">
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <ul class="dropdown">
            <li class="active"><%= link_to 'Sign Up', new_user_registration_path %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign Out",  destroy_user_session_path, :method => :delete %></li>
      <% end %>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="#">Left Nav Button</a></li>
    </ul>
  </section>

  <div class="top-bar-section">
    <ul>
    <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Portfolio" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Portfolio" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer class="row">

    </footer>
  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :technologies_used %><br />
    <%= f.text_area :technologies_used %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_projects.html.erb
<%= form_for task, remote: true do |f| %>
  <li class="project" id="<%= dom_id(project) %>">
    <h3><%= project.name %></h3>
    <p><%= project.technologies_used %></p>
    <div class="nav">
      <%= link_to 'Show', project %> |
      <%= link_to 'Edit', edit_project_path(project) %> |
      <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </li>
<% end %>

app/views/projects/create.js.erb
var ready = function () {
  $('#new_project').remove();
  $('#new-link').show();
  $('#projects-section').append('<%= j render(@project) %>');
};

$(document).ready(ready);
$(document).on('page:load', ready);

app/views/projects/destroy.js.erb
var ready = function () {
  $('#project_<%= @project.id %>').remove();
};

$(document).ready(ready);
$(document).on('page:load', ready);

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= render 'form' %>
<%= link_to 'Cancel', :back %>

app/views/projects/index.html.erb
 <h2>My Portfolio Projects</h2>
 <section class="row" id="projects-section">
  <ul>
    <% @projects.each do |project| %>
      <li class="project" id="<%= dom_id(project) %>">
        <h3><%= project.name %></h3>
        <p><%= project.technologies_used %></p>
        <div class="nav">
          <%= link_to 'Show', project %> |
          <%= link_to 'Edit', edit_project_path(project) %> |
          <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </li>
    <% end %>
  </ul>
  <br />
  <%= link_to 'New Project', new_project_path, id: 'new-link', remote: true %>
</section>

app/views/projects/new.html.erb
<h1>New project</h1>
<%= render 'form' %>
<%= link_to 'Back', projects_path %>

app/views/projects/new.js.erb
var ready = function () {
  $('#new-link').hide().after('<%= j render("form") %>');
};

$(document).ready(ready);
$(document).on('page:load', ready);

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p>Technologies used: <%=@project.technologies_used %></p>
<%= link_to 'Back', projects_path %> |
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Destroy', project_path(@project), method: :delete, data: {
                                               confirm: 'Are you sure?' } %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
</head>
<body>
   <div class="row">
    <div class="large-4 columns">
      <h1>Forrest Parker</h1>
      <h2>Web Developer</h2>
    </div>
    <div class="large-8 columns">
      <ul class="right button-group">
      <li><a href="https://github.com/fparker9676/" class="button"><img src="images/webicon-github.png"/></a></li>
      <li><a href="https://linkedin.com/in/forrestaparker" class="button"><img src="images/webicon-linkedin.png"/></a></li>
      <li><a href="#" class="button"><img src="images/webicon-aboutme.png"/></a></li>
      </ul>
     </div>
   </div>

  <div class="row">
    <h4>Showcase</h4>
    <div class="large-4 columns">
      <img src="http://placehold.it/400x300&text=[img]"/>
      <h4>Project Title</h4>
      <h5>Technologies used</h5>
      <p>
        Dessert soufflé applicake. Liquorice powder pudding. Marzipan liquorice pastry tootsie roll sugar plum. Sweet roll cake oat cake bonbon cookie macaroon caramels brownie jelly beans. Pudding donut croissant. Candy unerdwear.com unerdwear.com cookie candy tootsie roll fruitcake marzipan bonbon. Danish dessert caramels. Tiramisu halvah croissant bonbon pie liquorice sesame snaps ice cream pastry.
      </p>
    </div>

    <div class="large-4 columns">
      <img src="http://placehold.it/400x300&text=[img]"/>
      <h4>Project Title</h4>
      <h5>Technologies Used</h5>
      <p>Muffin jelly donut. Topping liquorice sweet jelly beans. Powder pie candy. Brownie jelly topping sweet topping muffin. Applicake bear claw candy canes jelly beans soufflé. Tart powder dragée. Bear claw lollipop apple pie cupcake gummies lollipop.</p>
    </div>

    <div class="large-4 columns">
      <img src="http://placehold.it/400x300&text=[img]"/>
      <h4>Project Title</h4>
      <h5>Technologies Used</h5>
      <p>Cupcake ipsum dolor. Sit amet unerdwear.com. Gingerbread macaroon chocolate bar apple pie caramels apple pie marshmallow. Sesame snaps I love topping biscuit halvah. Biscuit muffin chocolate bar macaroon tart cupcake fruitcake. Bonbon gummies donut I love cotton candy sweet roll powder cheesecake lemon drops.</p>
    </div>

    </div>


<div class="row">
    <div class="large-12 columns">

      <div class="panel">
        <h4>Get in touch!</h4>

        <div class="row">
          <div class="large-3 columns">
            <%= form_tag(welcome_contact_path, method: 'post', class:'forma') do %>
              <table>
                <thead></thead>
                <tbody>

                  <tr>
                    <td><%= label_tag(:name, 'Your Name') %></td>
                    <td><%= text_field_tag(:name) %></td>
                  </tr>

                  <tr>
                    <td><%= label_tag(:email, 'Email') %></td>
                    <td><%= text_field_tag(:email) %></td>
                  </tr>

                  <tr>
                    <td><%= label_tag(:message, 'Message') %></td>
                    <td><%= text_area_tag(:message) %></td>
                  </tr>

                  <tr>
                    <td><%= submit_tag('Send Email', class: 'button') %></td>
                  </tr>
                </tbody>
              </table>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>



  <footer class="row">
    <div class="large-12 columns">
      <hr/>
      <div class="row">
          <ul class="inline-list right">
            <li><a href="projects#index">Projects</a></li>
            <li><a href="articles#index">Articles</a></li>
            <li><a href="#">Some other link</a></li>
          </ul>
      </div>
    </div>
  </footer>

  <%= yield %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>